spring:
  application:
    name: ms-agend-schedule
    version: 1.0
    description: none
  activemq:
    broker-url: tcp://amq-agendamento-eletron-develop-tcp.amq-agendamento-eletron-develop.svc:61616?jms.prefetchPolicy.queuePrefetch=1
    user: admin
    password: admin
    close-timeout: 600000  
fixedDelay:
   milliseconds: 60000
queue.sms: medical.care.sms.queue
queue.push: medical.care.push.queue

database:
  url: jdbc:postgresql://provppp.chiusyo6mhnj.sa-east-1.rds.amazonaws.com:5432/provppp
  className: org.postgresql.Driver
  connectionTestQuery: 'SELECT 1'
  connectionTimeout: 20000
  maxLifetime: 600000
  maxPoolSize: 5
  packageName: br.com.sulamerica.susis.agendamento.model
br.sulamerica.cofresenha.oauth-request-cofres.1:
  id: 4362
  url: https://acessourgente.sulamerica.br/iso/coe/senha/4362?
  consumerKey: 5c8289c101173cae569b5c600ec9a01a05d1f6926
  consumerSecret: 7b1eb90ef3b610da2f19142c135e059d
  accessToken: 36340e08b40e88891742d2e5cdf2052005d1f6926
  access-token-secret: 6e3fe6724185b607b0a0b660b15ced89
server:
  port: 8080 
spring.jpa:
  jpa:
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  properties:
    hibernate: 
      temp.use_jdbc_metadata_defaults: false
      enable_lazy_load_no_trans: true