spring:
  application:
    name: ms-agend-schedule
    version: 1.0
    description: none
  activemq:
    broker-url: tcp://amq-agendamento-eletron-develop-tcp.amq-agendamento-eletron-develop.svc:61616?jms.prefetchPolicy.queuePrefetch=1
    user: admin
    password: admin
    close-timeout: 600000  
fixedDelay:
   milliseconds: 60000
queue.sms: medical.care.sms.queue
queue.push: medical.care.push.queue

database:
  url: jdbc:postgresql://provpph.chiusyo6mhnj.sa-east-1.rds.amazonaws.com:5432/provpph
  className: org.postgresql.Driver
  connectionTestQuery: 'SELECT 1'
  connectionTimeout: 20000
  maxLifetime: 600000
  maxPoolSize: 5
  packageName: br.com.sulamerica.susis.agendamento.model
br.sulamerica.cofresenha.oauth-request-cofres.1:
  id: 3522
  url: https://acessourgente.sulamerica.br/iso/coe/senha/3522?
  consumerKey: 42e4869907ef8dd53a5a12670f1ff79105c52f5dd
  consumerSecret: 4d3909bb1cca6e209ed8fc0cc9f59264
  accessToken: 43e0d34a9a8b42732b11cb999da91a9a05c52f5dd
  access-token-secret: 483ce98999ca74e64796cd8ad99d661d
server:
  port: 8080  
spring.jpa:
  jpa:
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  properties:
    hibernate: 
      temp.use_jdbc_metadata_defaults: false
      enable_lazy_load_no_trans: true